# -*- coding: utf-8 -*-
"""Homework4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KChnMvIZoe8e73gUKxUk95NqH2S3PqLH
"""

a = int(input('Enter the first number\n>>'))
b = int(input('Enter the second number\n>>'))
c = int(input('Enter the third number\n>>'))
print('Sum =', a + b + c)

b1 = int(input('Enter b1\n>>'))
q = float(input('Q is\n>>'))
n = int(input('n =\n>>'))
print('bn =', b1 * q**(n-1))

n = int(input('Enter the number:: '))
if n % 2 == 0:
    print('The number is even')
else:
    print('The nuber is odd')

a = int(input('Enter the first number\n>>'))
b = int(input('Enter the second number\n>>'))
c = int(input('Enter the third number\n>>'))
if c - b == b - a:
  print('arithmetic progression')
else:
  print('no pattern found')

a = int(input('Enter the number\n>>'))
if 100 <= a <= 999 and a % 161 == 0:
  print('Yes')
else: 
  print('No')

from math import sqrt
a = int(input('Enter a: '))
b = int(input('Enter b: '))
c = int(input('Enter c: '))

D = b**2 - 4 * a * c
if a != 0:
    if D > 0:
        x1 = (-b + sqrt(D)) / (2 * a)
        x2 = (-b - sqrt(D)) / (2 * a)
        print(f'{x1},\n{x2}1')

    elif D == 0:
        x = (-b) / (2 * a)
        print(x)
    else:
        print('No roots')
else:
    print('a cant be 0')

for i in range(1, 11, 1):
  print(f'7 * {i} = {7 * i}')

lst = []
n = int(input('n = '))
for i in range(n):
  number = int(input('Enter the number: '))
  lst.append(number)
print(lst)

num = int(input('Enter the number (1-1000): '))
for i in range(1,num+1):
  if num % i == 0:
    print(i)

num = int(input('How many numbers we have?: '))
k = 0
max = None
for i in range(num):
  numbers = int(input('Enter the number: '))
  if max is None:
    max = number
  elif numbers > max:
    k += 1
  max = numbers
print(k)

num = int(input('How many strings we have?: '))
lst = []
for i in range(num):
  strings = input('Enter a string! : ')
  lst.append(strings)
for i in range(num-1,-1,-1):
  print(lst[i])

a = int(input('Enter the number\n>>'))
p = 1
if a!= 0:
  for i in range(1, a+1):
    p *= i
  print(p)
else:
  print(1)

n = int(input('Enter the number\n>>'))
for i in range(1, n):
  if i**2<n:
    print(i**2, end = ' ')
  else:
    pass

n = int(input('Enter the number\n>>'))
i = 1
while i < n:
  print(i)
  i = i * 2

n = int(input('Enter the number\n>>'))
while n>1:
  if n % 2 != 0:
    print('No')
    break
  else:
    n = n/2
    if n == 1:
     print('Yes')

texts = []
while True:
  words = input('Enter words\n>>')
  if words == 'end' or words == 'End' or words == 'finish' or words =='Finish' or words == 'done' or words == 'Done':
    break
  else:
    texts.append(words)
for i in range(len(texts)):
  print(texts[i])

s = 0
while True:
  n = int(input('Enter the numbers\n>>'))
  if n >= 0:
    break
  else:
    s += n
print(s)

n = int(input('Enter the number\n>>'))
reversednum = 0
num = 0
while n != 0:
  num = n % 10
  n = n//10
  reversednum = reversednum * 10 + num
print(reversednum * 2)

n = int(input('Enter the number\n>>'))
while n > 0:
  lastnum = n%10
  num = (n // 10) % 10
  n = n//10
  if lastnum < num:
    print('No')
    break
  else:
    if 1<=n <=9:
      print('Yes')