# -*- coding: utf-8 -*-
"""Homework3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1p7PP5ZwWFz3yEl7S7LnhONKoZylmRAtG
"""

#1 
import sys
print(sys.version)

#2
import time
print(time.asctime())

#3
from math  import pi 
r = float(input('Enter the radius: '))
print('S = ', pi*r**2)

#4
filename = input('Enter the name; ')
print(filename.split('.')[-1])

#5
color_list = ["Red", "Green", "White", "Black"]
print (color_list[0], color_list[-1])

#6
exam_st_date = (11, 12, 2014)
print(f'{exam_st_date[0]}/{exam_st_date[1]}/{exam_st_date[2]}')

#7
n = int(input('Enter the digit! '))
print('S = ', n + (n*10 + n) + (n*100 + n*10 + n))
number = input('Enter the digit! ')
print(int(number) + int(number * 2) + int(number * 3))

#8
n = int(input('Enter the number:: '))
if n % 2 == 0:
    print('Even')
else:
    print('Odd')

#9
nums = [1, 5, 8, 3]
num = int(input('Enter the number! '))
print(num in nums)

#10
nums = [2, 3, 6, 5]
for i in nums:
  print(i * '*')

#11
color_list_1 = set(["White", "Black", "Red"])
color_list_2 = set(["Red", "Green"])
print(color_list_1 - color_list_2)

#12
lst = [1,4,5,6,7]
print(str(lst[0]) + str(lst[1]) +str(lst[2]) + str(lst[3]) + str(lst[4]))

#13
a = int(input('Enter first number: ')) 
b = int(input('Enter first number: '))
while a != b:
    if a > b:
        a -= b
    elif a < b:
        b -= a
print('gcd = ' ,a)

#14
a = int(input('Enter first number: ')) 
b = int(input('Enter first number: '))
m = a 
n = b
while a != b:
    if a > b:
        a -= b
    elif a < b:
        b -= a
print('lcm = ' , int(m * n / a))

#15
x1 = int(input('Enter x1: ')) 
y1 = int(input('Enter y1: '))
x2 = int(input('Enter x2: '))
y2 = int(input('Enter y2: '))

print(((x2 - x1)**2 + (y2 - y1)**2)**0.5)

#16
import os
print(os.getcwd())

#17
import struct
print(struct.calcsize("P") * 8)

#18 
import platform
print(platform.system())
print(platform.version())
print(platform.platform())
print(platform.release())

#19
import subprocess
import sys
result = subprocess.run([sys.executable, "-c", "raise ValueError('oops')"])
print (result)

#20
import multiprocessing
print(multiprocessing.cpu_count())

#21
import os
print(os.listdir())

#22
a = 8
b = 5
c = -3
print(min(a , b , c) , a + b + c - min(a , b , c) - max(a , b , c) , max(a , b , c))

#23

#24
num = [2, 3, 4, 5]
print(all(x > 3 for x in num))

#25
x = input('Specific character is . ')
string = input('Input string ')
print (string.count(x))

#26
path = '/users/system1/student1/homework-1.py'
print(path.split('/')[-1])
os.path.basename('/users/system1/student1/homework-1.py')

#27
lst = [2, 3, 6, 5]
lst.pop(0)
print(lst)

#28
try:
    x = float(input('Enter a number'))
except ValueError:
    print('Enter only numers')

#29
round(1/27, 2)

#30
text = 'Helllo Python Team'
for i in text: 
    if i.islower(): 
      print(True);
      break

#31
words = input('Enter a string ')
lst = []
for i in words:
  lst.append(i)
print(lst)

#32
import os.path
print(os.path.expanduser('~'))

#33
print(int(True))
print(int(False))

#34
x = 12
print(format(x, '08b'))
print(format(x, '010b'))

#35
lst = [-6 , 3 , 4, 2 ,1 ,-9 , 10 , 15]
maximum = lst[0]
minimum = lst[0]
for i in lst:
    if maximum < i:
        maximum = i
    if minimum > i:
        minimum = i

print(minimum , maximum)

#36
num = int(input('Enter the number : '))
s = 0
for i in range(num):
    s += i**3
print(s)